url: https://laurenscarzella.github.io
baseurl: "/td_solutions"

# Site settings
title: T&D Solutionz
email: zacharykskinner98@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Zachary Skinner
  pic: 1
  position: Founder & 3D Printing Specialist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/zachary-skinner-05943a134/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/trinkets.and.doodads/

# Postal address (add as many lines as necessary)
address:
  - line: 7400 E Golf Links Rd
  - line: Tucson, AZ 85730

# Build settings
markdown: kramdown
permalink: pretty